/*
    Copyright © 2020 r-neal-kelly, aka doticu
*/

#pragma once

#include "doticu_skylib/collections.h"
#include "doticu_skylib/cstring.h"
#include "doticu_skylib/enum.h"
#include "doticu_skylib/enum_type.h"
#include "doticu_skylib/interface.h"
#include "doticu_skylib/intrinsic.h"
#include "doticu_skylib/math.h"
#include "doticu_skylib/maybe.h"
#include "doticu_skylib/maybe_enum.h"
#include "doticu_skylib/numeric.h"
#include "doticu_skylib/skse.h"
#include "doticu_skylib/string.h"
#include "doticu_skylib/unique.h"
#include "doticu_skylib/version.h"

#include "doticu_skylib/sp8.h"
#include "doticu_skylib/sp16.h"
#include "doticu_skylib/sp32.h"
#include "doticu_skylib/sp64.h"
#include "doticu_skylib/sn8.h"
#include "doticu_skylib/sn16.h"
#include "doticu_skylib/sn32.h"
#include "doticu_skylib/sn64.h"

#include "doticu_skylib/alias_id.h"
#include "doticu_skylib/form_id.h"

namespace doticu_skylib {

    class Actor_Value_Modifier_e;
    class Actor_Value_Type_e;
    class Comparator_e;
    class Extra_Type_e;
    class Form_Type_e;
    class Logic_Gate_e;
    class Operator_e;
    class Package_Flags_e;
    class Package_Interrupt_Flags_e;
    class Rarity_e;
    class Relation_e;
    class Script_Type_e;
    class Sex_e;
    class Vitality_e;

    class Actor_Base_Data_c;
    class AI_c;
    class Attack_Damage_c;
    class Attack_Data_c;
    class Biped_Model_c;
    class Biped_Object_c;
    class Container_c;
    class Description_c;
    class Destructible_c;
    class Form_Data_c;
    class Harvest_c;
    class Keywords_c;
    class Leveled_c;
    class Model_c;
    class Model_Alternates_c;
    class Name_c;
    class Openable_c;
    class Package_Override_c;
    class Perks_c;
    class Race_c;
    class Skin_c;
    class Spells_c;

    class Active_Magic_Effect_t;
    class Actor_t;
    class Actor_Base_t;
    class Actor_State_t;
    class Actor_Values_t;
    class Alias_Base_t;
    class Alias_Reference_t;
    class Alpha_t;
    class Ammo_t;
    class Animated_Object_t;
    class Armor_t;
    class Armor_Set_t;
    class Book_t;
    class Bound_Object_t;
    class Cell_t;
    class Character_t;
    class Color_t;
    class Combat_Style_t;
    class Consts_t;
    class Container_t;
    class Dialogue_Branch_t;
    class Dialogue_Info_t;
    class Dialogue_Info_Instance_t;
    class Dialogue_Response_t;
    class Dialogue_Response_Instance_t;
    class Dialogue_Topic_t;
    class Effect_Shader_t;
    class Faction_t;
    class Faction_And_Rank_t;
    class Form_t;
    class Form_Factory_i;
    class Form_List_t;
    class Form_Owner_t;
    class Furniture_t;
    class Game_t;
    class Global_t;
    class Ingredient_t;
    class Keyword_t;
    class Leveled_Actor_Base_t;
    class Leveled_Item_t;
    class Location_t;
    class Magic_Base_t;
    class Magic_Effect_t;
    class Magic_Effect_Instance_t;
    class Magic_Target_t;
    class Memory_t;
    class Misc_t;
    class Mod_t;
    class Object_t;
    class OS_t;
    class Outfit_t;
    class Package_t;
    class Package_Data_t;
    class Package_Location_t;
    class Package_Schedule_t;
    class Package_Target_t;
    class Package_Value_t;
    class Package_Value_Bool_t;
    class Package_Value_Float_t;
    class Package_Value_Int_t;
    class Package_Value_Location_t;
    class Package_Value_Reference_t;
    class Package_Value_Target_t;
    class Package_Value_Topic_t;
    class Perk_t;
    class Player_t;
    class Player_Objective_t;
    class Potion_t;
    class Quest_t;
    class Race_t;
    class Reference_t;
    class Reference_Container_t;
    class Reference_Container_Entry_t;
    class Script_t;
    class Scroll_t;
    class SKSE_Plugin_t;
    class Spell_t;
    class Static_t;
    class Translations_t;
    class UI_t;
    class Voice_Type_t;
    class Weapon_t;
    class Worldspace_t;

    class Extra_Aliases_t;
    class Extra_Collision_Layer_t;
    class Extra_Container_Changes_t;
    class Extra_Count_t;
    class Extra_Data_t;
    class Extra_Encounter_Zone_t;
    class Extra_Factions_And_Ranks_t;
    class Extra_Flags_t;
    class Extra_Followers_t;
    class Extra_Ghost_t;
    class Extra_List_t;
    class Extra_Location_t;
    class Extra_Outfit_t;
    class Extra_Owner_t;
    class Extra_Reference_Interaction_t;
    class Extra_Soul_Level_t;
    class Extra_Talk_To_Player_t;
    class Extra_Text_Display_t;

}
