/*
    Copyright © 2020 r-neal-kelly, aka doticu
*/

#include "doticu_skylib/const_mods.h"
#include "doticu_skylib/const_weapons.h"
#include "doticu_skylib/game_macros.h"
#include "doticu_skylib/weapon.h"

namespace doticu_skylib { namespace Const { namespace Weapon {

    some<Weapon_t*> Battleaxe_Ancient_Nordic()                      { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x01CB64); }
    some<Weapon_t*> Battleaxe_Ancient_Nordic_Drainblood()           { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F82FA); }
    some<Weapon_t*> Battleaxe_Ancient_Nordic_Hero()                 { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x068C79); }
    some<Weapon_t*> Battleaxe_Ancient_Nordic_Honed()                { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x05BF12); }
    some<Weapon_t*> Battleaxe_Ancient_Nordic_Tsun_0()               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x05BF19); }
    some<Weapon_t*> Battleaxe_Ancient_Nordic_Tsun_1()               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x05BF16); }
    some<Weapon_t*> Battleaxe_Ancient_Nordic_Tsun_2()               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x05BF1A); }
    some<Weapon_t*> Battleaxe_Ancient_Nordic_Tsun_3()               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x05BF18); }
    some<Weapon_t*> Battleaxe_Ancient_Nordic_Wuuthrad()             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0956B5); }
    some<Weapon_t*> Battleaxe_Bound()                               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x058F5E); }
    some<Weapon_t*> Battleaxe_Bound_Mystic()                        { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0424F7); }
    some<Weapon_t*> Battleaxe_Daedric()                             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139B4); }
    some<Weapon_t*> Battleaxe_Dragonbone()                          { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x014FC3); }
    some<Weapon_t*> Battleaxe_Dragonbone_Keeper_0()                 { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x0113B7); }
    some<Weapon_t*> Battleaxe_Dragonbone_Keeper_1()                 { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x0113B8); }
    some<Weapon_t*> Battleaxe_Dragonbone_Keeper_2()                 { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x0113B9); }
    some<Weapon_t*> Battleaxe_Dragonbone_Keeper_3()                 { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x0113BA); }
    some<Weapon_t*> Battleaxe_Dragonbone_Keeper_4()                 { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x0113BB); }
    some<Weapon_t*> Battleaxe_Dragonbone_Wrathman()                 { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x014CA0); }
    some<Weapon_t*> Battleaxe_Dwarven()                             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x013994); }
    some<Weapon_t*> Battleaxe_Ebony()                               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139AC); }
    some<Weapon_t*> Battleaxe_Ebony_Rueful_Axe()                    { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x01C4E6); }
    some<Weapon_t*> Battleaxe_Elven()                               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x01399C); }
    some<Weapon_t*> Battleaxe_Glass()                               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139A4); }
    some<Weapon_t*> Battleaxe_Iron()                                { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x013980); }
    some<Weapon_t*> Battleaxe_Iron_Executioner()                    { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0BE25E); }
    some<Weapon_t*> Battleaxe_Iron_Woodsmans_Friend()               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x022265); }
    some<Weapon_t*> Battleaxe_Orcish()                              { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x01398C); }
    some<Weapon_t*> Battleaxe_Steel()                               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x013984); }
    some<Weapon_t*> Battleaxe_Steel_Skyforge()                      { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x09F25F); }

    some<Weapon_t*> Bow_Ancient_Nordic()                            { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0302CA); }
    some<Weapon_t*> Bow_Ancient_Nordic_Drainspell()                 { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F82FC); }
    some<Weapon_t*> Bow_Ancient_Nordic_Gauldur_Blackbow_0()         { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0A5DEF); }
    some<Weapon_t*> Bow_Ancient_Nordic_Gauldur_Blackbow_1()         { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F5D1F); }
    some<Weapon_t*> Bow_Ancient_Nordic_Gauldur_Blackbow_2()         { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F5D20); }
    some<Weapon_t*> Bow_Ancient_Nordic_Gauldur_Blackbow_3()         { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F5D21); }
    some<Weapon_t*> Bow_Ancient_Nordic_Gauldur_Blackbow_4()         { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F5D22); }
    some<Weapon_t*> Bow_Ancient_Nordic_Gauldur_Blackbow_NPC()       { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0A5DF0); }
    some<Weapon_t*> Bow_Ancient_Nordic_Hero()                       { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x068C57); }
    some<Weapon_t*> Bow_Ancient_Nordic_Supple()                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x05D179); }
    some<Weapon_t*> Bow_Bound()                                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x058F60); }
    some<Weapon_t*> Bow_Bound_Mystic()                              { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0424F8); }
    some<Weapon_t*> Bow_Daedric()                                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139B5); }
    some<Weapon_t*> Bow_Dragonbone()                                { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x0176F1); }
    some<Weapon_t*> Bow_Dragonbone_Keeper_0()                       { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x01A179); }
    some<Weapon_t*> Bow_Dragonbone_Keeper_1()                       { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x01A17A); }
    some<Weapon_t*> Bow_Dragonbone_Keeper_2()                       { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x01A17B); }
    some<Weapon_t*> Bow_Dragonbone_Keeper_3()                       { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x01A17C); }
    some<Weapon_t*> Bow_Dragonbone_Keeper_4()                       { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x01A17D); }
    some<Weapon_t*> Bow_Dwarven()                                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x013995); }
    some<Weapon_t*> Bow_Dwarven_Sphere_Crossbow_0()                 { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x07F6DF); }
    some<Weapon_t*> Bow_Dwarven_Sphere_Crossbow_1()                 { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x10EC8A); }
    some<Weapon_t*> Bow_Dwarven_Zephyr()                            { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00CFB6); }
    some<Weapon_t*> Bow_Dwarven_Zephyr_NPC()                        { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00CFB5); }
    some<Weapon_t*> Bow_Ebony()                                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139AD); }
    some<Weapon_t*> Bow_Ebony_Nightingale_0()                       { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x07E5C3); }
    some<Weapon_t*> Bow_Ebony_Nightingale_1()                       { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F6529); }
    some<Weapon_t*> Bow_Ebony_Nightingale_2()                       { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F652A); }
    some<Weapon_t*> Bow_Ebony_Nightingale_3()                       { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F652B); }
    some<Weapon_t*> Bow_Ebony_Nightingale_4()                       { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F652C); }
    some<Weapon_t*> Bow_Ebony_Nightingale_NPC()                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0DEED8); }
    some<Weapon_t*> Bow_Elven()                                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x01399D); }
    some<Weapon_t*> Bow_Elven_Auriel()                              { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x000800); }
    some<Weapon_t*> Bow_Elven_Firiniels_End()                       { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x017059); }
    some<Weapon_t*> Bow_Falmer()                                    { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x038340); }
    some<Weapon_t*> Bow_Falmer_Supple()                             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x083167); }
    some<Weapon_t*> Bow_Forsworn()                                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0CEE9B); }
    some<Weapon_t*> Bow_Glass()                                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139A5); }
    some<Weapon_t*> Bow_Iron_Imperial()                             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x013841); }
    some<Weapon_t*> Bow_Orcish()                                    { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x01398D); }
    some<Weapon_t*> Bow_Steel_Angi()                                { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0CC392); }
    some<Weapon_t*> Bow_Steel_Dravin()                              { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x06B9AD); }
    some<Weapon_t*> Bow_Steel_Follower()                            { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x10E2DD); }
    some<Weapon_t*> Bow_Steel_Hunt()                                { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0AB705); }
    some<Weapon_t*> Bow_Steel_Hunting()                             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x013985); }
    some<Weapon_t*> Bow_Wood_Froki()                                { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0C0186); }
    some<Weapon_t*> Bow_Wood_Long()                                 { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x03B562); }

    some<Weapon_t*> Crossbow_Dwarven()                              { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00B647); }
    some<Weapon_t*> Crossbow_Dwarven_Enhanced()                     { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00F19F); }
    some<Weapon_t*> Crossbow_Dwarven_Fire_1_Scorching()             { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0DB); }
    some<Weapon_t*> Crossbow_Dwarven_Fire_2_Fire()                  { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0DC); }
    some<Weapon_t*> Crossbow_Dwarven_Fire_3_Blaze()                 { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0DD); }
    some<Weapon_t*> Crossbow_Dwarven_Magicka_1_Diminishing()        { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0D8); }
    some<Weapon_t*> Crossbow_Dwarven_Magicka_2_Depleting()          { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0D9); }
    some<Weapon_t*> Crossbow_Dwarven_Magicka_3_Enervating()         { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0DA); }
    some<Weapon_t*> Crossbow_Dwarven_Paralyze_1_Stunning()          { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0D6); }
    some<Weapon_t*> Crossbow_Dwarven_Paralyze_2_Immobilizing()      { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0D7); }
    some<Weapon_t*> Crossbow_Dwarven_Shock_1_Shocks()               { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0D3); }
    some<Weapon_t*> Crossbow_Dwarven_Shock_2_Thunderbolts()         { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0D4); }
    some<Weapon_t*> Crossbow_Dwarven_Shock_3_Lightning()            { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0D5); }
    some<Weapon_t*> Crossbow_Dwarven_Soul_Trap_1_Binding()          { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0D0); }
    some<Weapon_t*> Crossbow_Dwarven_Soul_Trap_2_Animus()           { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0D1); }
    some<Weapon_t*> Crossbow_Dwarven_Soul_Trap_3_Malediction()      { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0D2); }
    some<Weapon_t*> Crossbow_Dwarven_Turn_Undead_1_Reverent()       { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0CD); }
    some<Weapon_t*> Crossbow_Dwarven_Turn_Undead_2_Hallowed()       { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0CE); }
    some<Weapon_t*> Crossbow_Dwarven_Turn_Undead_3_Virtuous()       { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0CF); }
    some<Weapon_t*> Crossbow_Steel()                                { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x000801); }
    some<Weapon_t*> Crossbow_Steel_Enhanced()                       { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00F19E); }
    some<Weapon_t*> Crossbow_Steel_Fire_1_Embers()                  { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0CA); }
    some<Weapon_t*> Crossbow_Steel_Fire_2_Burning()                 { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0CB); }
    some<Weapon_t*> Crossbow_Steel_Fire_3_Scorching()               { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0CC); }
    some<Weapon_t*> Crossbow_Steel_Magicka_1_Sapping()              { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0C6); }
    some<Weapon_t*> Crossbow_Steel_Magicka_2_Draining()             { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0C7); }
    some<Weapon_t*> Crossbow_Steel_Magicka_3_Diminishing()          { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0C9); }
    some<Weapon_t*> Crossbow_Steel_Shock_1_Sparks()                 { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0C3); }
    some<Weapon_t*> Crossbow_Steel_Shock_2_Arcing()                 { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0C4); }
    some<Weapon_t*> Crossbow_Steel_Shock_3_Shocks()                 { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0C5); }
    some<Weapon_t*> Crossbow_Steel_Soul_Trap_1_Souls()              { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0C0); }
    some<Weapon_t*> Crossbow_Steel_Soul_Trap_2_Soul_Snares()        { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0C1); }
    some<Weapon_t*> Crossbow_Steel_Soul_Trap_3_Binding()            { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0C2); }
    some<Weapon_t*> Crossbow_Steel_Turn_Undead_1_Blessed()          { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0BD); }
    some<Weapon_t*> Crossbow_Steel_Turn_Undead_2_Sanctified()       { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0BE); }
    some<Weapon_t*> Crossbow_Steel_Turn_Undead_3_Reverent()         { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D0BF); }

    some<Weapon_t*> Dagger_Ancient_Nordic_Dragon_Priest()           { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x01C1FE); }
    some<Weapon_t*> Dagger_Ancient_Nordic_Kahvozeins_Fang()         { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0D0758); }
    some<Weapon_t*> Dagger_Daedric()                                { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139B6); }
    some<Weapon_t*> Dagger_Daedric_Mehrunes_Razor()                 { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0240D2); }
    some<Weapon_t*> Dagger_Dragonbone()                             { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x014FCB); }
    some<Weapon_t*> Dagger_Dwarven()                                { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x013996); }
    some<Weapon_t*> Dagger_Dwarven_Keening()                        { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x06A13C); }
    some<Weapon_t*> Dagger_Ebony()                                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139AE); }
    some<Weapon_t*> Dagger_Ebony_Blade_Of_Sacrifice()               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x079B1D); }
    some<Weapon_t*> Dagger_Ebony_Nettlebane()                       { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x01C492); }
    some<Weapon_t*> Dagger_Elven()                                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x01399E); }
    some<Weapon_t*> Dagger_Elven_Borvir()                           { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0ECD54); }
    some<Weapon_t*> Dagger_Elven_Prelate()                          { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x01681F); }
    some<Weapon_t*> Dagger_Glass()                                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139A6); }
    some<Weapon_t*> Dagger_Iron()                                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x01397E); }
    some<Weapon_t*> Dagger_Iron_Alessandra()                        { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x043E1E); }
    some<Weapon_t*> Dagger_Iron_Fork()                              { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x01F25B); }
    some<Weapon_t*> Dagger_Iron_Knife()                             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x01F25A); }
    some<Weapon_t*> Dagger_Iron_Shiv()                              { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0426C8); }
    some<Weapon_t*> Dagger_Orcish()                                 { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x01398E); }
    some<Weapon_t*> Dagger_Steel()                                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x013986); }
    some<Weapon_t*> Dagger_Steel_Blade_Of_Woe()                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x09CCDC); }
    some<Weapon_t*> Dagger_Steel_Blade_Of_Woe_Astrid()              { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0964C9); }
    some<Weapon_t*> Dagger_Steel_Bloodthorn()                       { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0A4DCE); }
    some<Weapon_t*> Dagger_Steel_Rundi()                            { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0ECD53); }
    some<Weapon_t*> Dagger_Steel_Skyforge()                         { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x09F25D); }
    some<Weapon_t*> Dagger_Steel_Skyforge_NPC()                     { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00CFB4); }
    some<Weapon_t*> Dagger_Steel_Valdrs_Lucky()                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0B994E); }

    some<Weapon_t*> Greatsword_Ancient_Nordic()                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0236A5); }
    some<Weapon_t*> Greatsword_Ancient_Nordic_Hero()                { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0A3115); }
    some<Weapon_t*> Greatsword_Ancient_Nordic_Honed()               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x05BF13); }
    some<Weapon_t*> Greatsword_Daedric()                            { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139B7); }
    some<Weapon_t*> Greatsword_Daedric_Ebony_Blade()                { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x04A38F); }
    some<Weapon_t*> Greatsword_Daedric_Ebony_Blade_Full()           { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0EA29C); }
    some<Weapon_t*> Greatsword_Daedric_Scorching()                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x017288); }
    some<Weapon_t*> Greatsword_Dragonbone()                         { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x014FCC); }
    some<Weapon_t*> Greatsword_Dragonbone_Wrathman()                { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x014C9F); }
    some<Weapon_t*> Greatsword_Dwarven()                            { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x013997); }
    some<Weapon_t*> Greatsword_Ebony()                              { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139AF); }
    some<Weapon_t*> Greatsword_Elven()                              { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x01399F); }
    some<Weapon_t*> Greatsword_Glass()                              { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139A7); }
    some<Weapon_t*> Greatsword_Iron()                               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x01359D); }
    some<Weapon_t*> Greatsword_Orcish()                             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x01398F); }
    some<Weapon_t*> Greatsword_Silver()                             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x10C6FB); }
    some<Weapon_t*> Greatsword_Steel()                              { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x013987); }
    some<Weapon_t*> Greatsword_Steel_Balgruuf()                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0946FC); }
    some<Weapon_t*> Greatsword_Steel_Skyforge()                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x09F25E); }

    some<Weapon_t*> Mace_Daedric()                                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139B8); }
    some<Weapon_t*> Mace_Daedric_Inferno()                          { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x10FD5E); }
    some<Weapon_t*> Mace_Daedric_Molag_Bal()                        { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0233E3); }
    some<Weapon_t*> Mace_Daedric_Molag_Bal_Rusty()                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x022F0F); }
    some<Weapon_t*> Mace_Dragonbone()                               { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x014FCD); }
    some<Weapon_t*> Mace_Dragonbone_Keeper_0()                      { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x01A173); }
    some<Weapon_t*> Mace_Dragonbone_Keeper_1()                      { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x01A174); }
    some<Weapon_t*> Mace_Dragonbone_Keeper_2()                      { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x01A175); }
    some<Weapon_t*> Mace_Dragonbone_Keeper_3()                      { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x01A176); }
    some<Weapon_t*> Mace_Dragonbone_Keeper_4()                      { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x01A177); }
    some<Weapon_t*> Mace_Dwarven()                                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x013998); }
    some<Weapon_t*> Mace_Ebony()                                    { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139B0); }
    some<Weapon_t*> Mace_Elven()                                    { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139A0); }
    some<Weapon_t*> Mace_Elven_Prelate()                            { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x01681E); }
    some<Weapon_t*> Mace_Glass()                                    { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139A8); }
    some<Weapon_t*> Mace_Iron()                                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x013982); }
    some<Weapon_t*> Mace_Iron_Lunar_0()                             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x03B0BF); }
    some<Weapon_t*> Mace_Iron_Lunar_1()                             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x03B0C0); }
    some<Weapon_t*> Mace_Iron_Lunar_2()                             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x03B0C1); }
    some<Weapon_t*> Mace_Orcish()                                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x013990); }
    some<Weapon_t*> Mace_Steel()                                    { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x013988); }
    some<Weapon_t*> Mace_Steel_Lunar_0()                            { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x03B0B6); }
    some<Weapon_t*> Mace_Steel_Lunar_1()                            { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x03B0B9); }
    some<Weapon_t*> Mace_Steel_Lunar_2()                            { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x03B0BC); }

    some<Weapon_t*> Staff_Alteration()                              { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x07E646); }
    some<Weapon_t*> Staff_Alteration_Magelight()                    { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0BE121); }
    some<Weapon_t*> Staff_Alteration_Paralysis()                    { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B73); }

    some<Weapon_t*> Staff_Conjuration()                             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x07E647); }
    some<Weapon_t*> Staff_Conjuration_Banishing()                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B79); }
    some<Weapon_t*> Staff_Conjuration_Daedric_Command()             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B7B); }
    some<Weapon_t*> Staff_Conjuration_Dread_Zombies()               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B7C); }
    some<Weapon_t*> Staff_Conjuration_Expulsion()                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B7E); }
    some<Weapon_t*> Staff_Conjuration_Familiar()                    { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B75); }
    some<Weapon_t*> Staff_Conjuration_Flame_Atronach()              { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B78); }
    some<Weapon_t*> Staff_Conjuration_Frost_Atronach()              { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0BE120); }
    some<Weapon_t*> Staff_Conjuration_Reanimation()                 { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B76); }
    some<Weapon_t*> Staff_Conjuration_Revenants()                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B7A); }
    some<Weapon_t*> Staff_Conjuration_Sild()                        { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0A88C9); }
    some<Weapon_t*> Staff_Conjuration_Soul_Trapping()               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0BE122); }
    some<Weapon_t*> Staff_Conjuration_Storm_Atronach()              { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B7D); }
    some<Weapon_t*> Staff_Conjuration_Zombies()                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B74); }
    
    some<Weapon_t*> Staff_Daedric_Sanguine_Rose()                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x01CB36); }
    some<Weapon_t*> Staff_Daedric_Sanguine_Rose_Broken()            { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x01CB30); }
    some<Weapon_t*> Staff_Daedric_Skull_Of_Corruption()             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x035066); }
    some<Weapon_t*> Staff_Daedric_Wabbajack()                       { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x02AC6F); }
    some<Weapon_t*> Staff_Daedric_Wabbajack_Quest()                 { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x09B2B2); }

    some<Weapon_t*> Staff_Destruction()                             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0BE11F); }
    some<Weapon_t*> Staff_Destruction_Chain_Lightning()             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B84); }
    some<Weapon_t*> Staff_Destruction_Fireballs()                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B82); }
    some<Weapon_t*> Staff_Destruction_Firebolts()                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x04C6CA); }
    some<Weapon_t*> Staff_Destruction_Flame_Wall()                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B85); }
    some<Weapon_t*> Staff_Destruction_Flames()                      { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x04DEE0); }
    some<Weapon_t*> Staff_Destruction_Frost_Wall()                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B86); }
    some<Weapon_t*> Staff_Destruction_Frostbite()                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x04DEE1); }
    some<Weapon_t*> Staff_Destruction_Ice_Spikes()                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x04DED8); }
    some<Weapon_t*> Staff_Destruction_Ice_Storms()                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B83); }
    some<Weapon_t*> Staff_Destruction_Icy_Spear()                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x10FCF7); }
    some<Weapon_t*> Staff_Destruction_Incineration()                { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x10FCF2); }
    some<Weapon_t*> Staff_Destruction_Lightning_Bolts()             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x04DEE3); }
    some<Weapon_t*> Staff_Destruction_Sparks()                      { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x04DEE2); }
    some<Weapon_t*> Staff_Destruction_Storm_Wall()                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B87); }
    some<Weapon_t*> Staff_Destruction_Thunderbolts()                { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x10FCF4); }
    
    some<Weapon_t*> Staff_Dragon_Priest_0()                         { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x04DE5B); }
    some<Weapon_t*> Staff_Dragon_Priest_1_Necromantic()             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0284F5); }
    some<Weapon_t*> Staff_Dragon_Priest_1_Tandil()                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x06A093); }
    some<Weapon_t*> Staff_Dragon_Priest_2()                         { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x07E5BB); }
    some<Weapon_t*> Staff_Dragon_Priest_2_Hevnoraak()               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x10076D); }

    some<Weapon_t*> Staff_Dwarven_Aetherial()                       { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00575E); }
    some<Weapon_t*> Staff_Dwarven_Spider_Control_Rod()              { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0E57F0); }
    some<Weapon_t*> Staff_Dwarven_Spider_Control_Rod_Fake()         { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0C19FF); }

    some<Weapon_t*> Staff_Falmer()                                  { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x003629); }
    some<Weapon_t*> Staff_Falmer_Chain_Lightning()                  { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x011D56); }
    some<Weapon_t*> Staff_Falmer_Fireballs()                        { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x011D57); }
    some<Weapon_t*> Staff_Falmer_Firebolts()                        { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x011D5D); }
    some<Weapon_t*> Staff_Falmer_Flame_Atronach()                   { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x011D58); }
    some<Weapon_t*> Staff_Falmer_Frost_Atronach()                   { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x011D59); }
    some<Weapon_t*> Staff_Falmer_Ice_Spikes()                       { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x011D5E); }
    some<Weapon_t*> Staff_Falmer_Ice_Storms()                       { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x011D5F); }
    some<Weapon_t*> Staff_Falmer_Lightning_Bolts()                  { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x011D60); }

    some<Weapon_t*> Staff_Forsworn()                                { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0CC826); }
    some<Weapon_t*> Staff_Forsworn_Eye_Of_Melka()                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0B3DFA); }
    some<Weapon_t*> Staff_Forsworn_Flames()                         { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0FA2C1); }
    some<Weapon_t*> Staff_Forsworn_Hags_Wrath()                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x07A4FB); }

    some<Weapon_t*> Staff_Illusion()                                { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x07A91B); }
    some<Weapon_t*> Staff_Illusion_Arcane_Authority()               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0940D8); }
    some<Weapon_t*> Staff_Illusion_Calm()                           { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B8B); }
    some<Weapon_t*> Staff_Illusion_Charming()                       { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B91); }
    some<Weapon_t*> Staff_Illusion_Courage()                        { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B88); }
    some<Weapon_t*> Staff_Illusion_Fear()                           { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B8C); }
    some<Weapon_t*> Staff_Illusion_Frenzy()                         { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B8F); }
    some<Weapon_t*> Staff_Illusion_Fury()                           { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B89); }
    some<Weapon_t*> Staff_Illusion_Gadnors_Charming()               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x046E0B); }
    some<Weapon_t*> Staff_Illusion_Halldir()                        { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0AB704); }
    some<Weapon_t*> Staff_Illusion_Inspiration()                    { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B8E); }
    some<Weapon_t*> Staff_Illusion_Ruunvald()                       { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x01958C); }
    some<Weapon_t*> Staff_Illusion_Vanquishment()                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B92); }

    some<Weapon_t*> Staff_Magnus()                                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x035369); }

    some<Weapon_t*> Staff_Restoration()                             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x051B0C); }
    some<Weapon_t*> Staff_Restoration_Healing_Hand()                { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B93); }
    some<Weapon_t*> Staff_Restoration_Jyrik_Gauldurson()            { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0E5F43); }
    some<Weapon_t*> Staff_Restoration_Mending()                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B99); }
    some<Weapon_t*> Staff_Restoration_Repulsion()                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B9A); }
    some<Weapon_t*> Staff_Restoration_Repulsion_Grand()             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B9B); }
    some<Weapon_t*> Staff_Restoration_Turning()                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B95); }
    some<Weapon_t*> Staff_Restoration_Turning_Grand()               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B97); }
    some<Weapon_t*> Staff_Restoration_Turning_Minor()               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x029B94); }

    some<Weapon_t*> Sword_Ancient_Nordic()                          { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x02C66F); }
    some<Weapon_t*> Sword_Ancient_Nordic_Ceremonial()               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x08ADFC); }
    some<Weapon_t*> Sword_Ancient_Nordic_Drainheart()               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F71DD); }
    some<Weapon_t*> Sword_Ancient_Nordic_Eduj()                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x08FFDF); }
    some<Weapon_t*> Sword_Ancient_Nordic_Gauldur_Blackblade_0()     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0AB702); }
    some<Weapon_t*> Sword_Ancient_Nordic_Gauldur_Blackblade_1()     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F5D1A); }
    some<Weapon_t*> Sword_Ancient_Nordic_Gauldur_Blackblade_2()     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F5D1B); }
    some<Weapon_t*> Sword_Ancient_Nordic_Gauldur_Blackblade_3()     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F5D1C); }
    some<Weapon_t*> Sword_Ancient_Nordic_Gauldur_Blackblade_4()     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F5D1D); }
    some<Weapon_t*> Sword_Ancient_Nordic_Ghostblade()               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x094A2B); }
    some<Weapon_t*> Sword_Ancient_Nordic_Hero()                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x068C7B); }
    some<Weapon_t*> Sword_Ancient_Nordic_Hjalti()                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x068976); }
    some<Weapon_t*> Sword_Ancient_Nordic_Honed()                    { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x05BF14); }
    some<Weapon_t*> Sword_Ancient_Nordic_Pale_Blade_0()             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0D37CE); }
    some<Weapon_t*> Sword_Ancient_Nordic_Pale_Blade_1()             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F5D2A); }
    some<Weapon_t*> Sword_Ancient_Nordic_Pale_Blade_2()             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F5D2B); }
    some<Weapon_t*> Sword_Ancient_Nordic_Pale_Blade_3()             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F5D2C); }
    some<Weapon_t*> Sword_Ancient_Nordic_Pale_Blade_4()             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F5D2D); }
    some<Weapon_t*> Sword_Ancient_Nordic_Red_Eagles_Bane()          { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0AB703); }
    some<Weapon_t*> Sword_Ancient_Nordic_Red_Eagles_Fury()          { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x09FD50); }
    some<Weapon_t*> Sword_Bound()                                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x058F5F); }
    some<Weapon_t*> Sword_Bound_Mystic()                            { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0424F9); }
    some<Weapon_t*> Sword_Bound_Phantom()                           { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0771B9); }
    some<Weapon_t*> Sword_Bound_Right_Hand()                        { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0BA30E); }
    some<Weapon_t*> Sword_Daedric()                                 { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139B9); }
    some<Weapon_t*> Sword_Daedric_Dawnbreaker()                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x04E4EE); }
    some<Weapon_t*> Sword_Dragonbone()                              { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x014FCE); }
    some<Weapon_t*> Sword_Dragonbone_Keeper_0()                     { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x01A180); }
    some<Weapon_t*> Sword_Dragonbone_Keeper_1()                     { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x01A181); }
    some<Weapon_t*> Sword_Dragonbone_Keeper_2()                     { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x01A182); }
    some<Weapon_t*> Sword_Dragonbone_Keeper_3()                     { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x01A183); }
    some<Weapon_t*> Sword_Dragonbone_Keeper_4()                     { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x01A184); }
    some<Weapon_t*> Sword_Dwarven()                                 { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x013999); }
    some<Weapon_t*> Sword_Ebony()                                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139B1); }
    some<Weapon_t*> Sword_Ebony_Nightingale_0()                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x07A917); }
    some<Weapon_t*> Sword_Ebony_Nightingale_1()                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F6524); }
    some<Weapon_t*> Sword_Ebony_Nightingale_2()                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F6525); }
    some<Weapon_t*> Sword_Ebony_Nightingale_3()                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F6526); }
    some<Weapon_t*> Sword_Ebony_Nightingale_4()                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F6527); }
    some<Weapon_t*> Sword_Ebony_Nightingale_NPC()                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0DEED7); }
    some<Weapon_t*> Sword_Elven()                                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139A1); }
    some<Weapon_t*> Sword_Elven_Herebanes_Courage()                 { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F9648); }
    some<Weapon_t*> Sword_Falmer()                                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x02E6D1); }
    some<Weapon_t*> Sword_Falmer_Honed()                            { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x06F6FF); }
    some<Weapon_t*> Sword_Forsworn()                                { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0CADE9); }
    some<Weapon_t*> Sword_Glass()                                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139A9); }
    some<Weapon_t*> Sword_Glass_Chillrend_0()                       { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F8313); }
    some<Weapon_t*> Sword_Glass_Chillrend_1()                       { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F8314); }
    some<Weapon_t*> Sword_Glass_Chillrend_2()                       { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F8315); }
    some<Weapon_t*> Sword_Glass_Chillrend_3()                       { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F8316); }
    some<Weapon_t*> Sword_Glass_Chillrend_4()                       { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F8317); }
    some<Weapon_t*> Sword_Glass_Chillrend_5()                       { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F8318); }
    some<Weapon_t*> Sword_Glass_Grimsever()                         { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x053379); }
    some<Weapon_t*> Sword_Iron()                                    { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x012EB7); }
    some<Weapon_t*> Sword_Iron_Amazement()                          { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x013135); }
    some<Weapon_t*> Sword_Iron_Amrens_Family()                      { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0647AC); }
    some<Weapon_t*> Sword_Iron_Lunar_0()                            { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x03B0C2); }
    some<Weapon_t*> Sword_Iron_Lunar_1()                            { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x03B0C3); }
    some<Weapon_t*> Sword_Iron_Lunar_2()                            { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x03B0C4); }
    some<Weapon_t*> Sword_Orcish()                                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x013991); }
    some<Weapon_t*> Sword_Silver()                                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x10AA19); }
    some<Weapon_t*> Sword_Steel()                                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x013989); }
    some<Weapon_t*> Sword_Steel_Blades()                            { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x03AEB9); }
    some<Weapon_t*> Sword_Steel_Bolars_Oathblade()                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0C1989); }
    some<Weapon_t*> Sword_Steel_Dexion_Evicus()                     { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x014555); }
    some<Weapon_t*> Sword_Steel_Dragonbane_0()                      { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F1AC1); }
    some<Weapon_t*> Sword_Steel_Dragonbane_1()                      { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F71CD); }
    some<Weapon_t*> Sword_Steel_Dragonbane_2()                      { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F71CE); }
    some<Weapon_t*> Sword_Steel_Dragonbane_3()                      { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F71CF); }
    some<Weapon_t*> Sword_Steel_Dragonbane_4()                      { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0F71D0); }
    some<Weapon_t*> Sword_Steel_Harkon()                            { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x0067CF); }
    some<Weapon_t*> Sword_Steel_Harrald()                           { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0557F5); }
    some<Weapon_t*> Sword_Steel_Imperial()                          { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0135B8); }
    some<Weapon_t*> Sword_Steel_Lunar_0()                           { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x03B0B7); }
    some<Weapon_t*> Sword_Steel_Lunar_1()                           { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x03B0BA); }
    some<Weapon_t*> Sword_Steel_Lunar_2()                           { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x03B0BD); }
    some<Weapon_t*> Sword_Steel_Queen_Freydis()                     { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0AB85D); }
    some<Weapon_t*> Sword_Steel_Scimitar()                          { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x07A91A); }
    some<Weapon_t*> Sword_Steel_Skyforge()                          { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x09F25C); }
    some<Weapon_t*> Sword_Steel_Windshear()                         { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x06EA8B); }
    some<Weapon_t*> Sword_Wooden()                                  { DEFINE_FORM(Const::Mod::Hearthfires(),    Weapon_t, 0x004D91); }

    some<Weapon_t*> Unarmed()                                       { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0001F4); }

    some<Weapon_t*> Waraxe_Ancient_Nordic()                         { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x02C672); }
    some<Weapon_t*> Waraxe_Ancient_Nordic_Ceremonial()              { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x08ADFB); }
    some<Weapon_t*> Waraxe_Ancient_Nordic_Hero()                    { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x068C63); }
    some<Weapon_t*> Waraxe_Ancient_Nordic_Honed()                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x05BF15); }
    some<Weapon_t*> Waraxe_Ancient_Nordic_Illusory()                { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0E7A31); }
    some<Weapon_t*> Waraxe_Ancient_Nordic_Okin()                    { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x08FFDE); }
    some<Weapon_t*> Waraxe_Daedric()                                { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139B3); }
    some<Weapon_t*> Waraxe_Dragonbone()                             { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x014FCF); }
    some<Weapon_t*> Waraxe_Dwarven()                                { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x013993); }
    some<Weapon_t*> Waraxe_Ebony()                                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139AB); }
    some<Weapon_t*> Waraxe_Elven()                                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x01399B); }
    some<Weapon_t*> Waraxe_Falmer()                                 { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0302CD); }
    some<Weapon_t*> Waraxe_Falmer_Honed()                           { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x06F700); }
    some<Weapon_t*> Waraxe_Forsworn()                               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0CC829); }
    some<Weapon_t*> Waraxe_Forsworn_Briarheart_Geis()               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0AE087); }
    some<Weapon_t*> Waraxe_Glass()                                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139A3); }
    some<Weapon_t*> Waraxe_Iron()                                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x013790); }
    some<Weapon_t*> Waraxe_Iron_Ghorbashs_Ancestral()               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x06A8FD); }
    some<Weapon_t*> Waraxe_Iron_Lunar_0()                           { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x03B0C5); }
    some<Weapon_t*> Waraxe_Iron_Lunar_1()                           { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x03B0C6); }
    some<Weapon_t*> Waraxe_Iron_Lunar_2()                           { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x03B0C7); }
    some<Weapon_t*> Waraxe_Iron_Pickaxe()                           { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0E3C16); }
    some<Weapon_t*> Waraxe_Iron_Pickaxe_Notched()                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x1019D4); }
    some<Weapon_t*> Waraxe_Iron_Poacher()                           { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0AE086); }
    some<Weapon_t*> Waraxe_Iron_Rocksplinter()                      { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x06A707); }
    some<Weapon_t*> Waraxe_Iron_Woodcutter()                        { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x02F2F4); }
    some<Weapon_t*> Waraxe_Orcish()                                 { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x01398B); }
    some<Weapon_t*> Waraxe_Steel()                                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x013983); }
    some<Weapon_t*> Waraxe_Steel_Dawnguard()                        { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00D098); }
    some<Weapon_t*> Waraxe_Steel_Dawnguard_Rune()                   { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x01668C); }
    some<Weapon_t*> Waraxe_Steel_Lunar_0()                          { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x03B0B8); }
    some<Weapon_t*> Waraxe_Steel_Lunar_1()                          { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x03B0BB); }
    some<Weapon_t*> Waraxe_Steel_Lunar_2()                          { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x03B0BE); }
    some<Weapon_t*> Waraxe_Steel_Skyforge()                         { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x09F260); }

    some<Weapon_t*> Warhammer_Daedric()                             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139BA); }
    some<Weapon_t*> Warhammer_Daedric_Volendrung()                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x02ACD2); }
    some<Weapon_t*> Warhammer_Dragonbone()                          { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x014FD0); }
    some<Weapon_t*> Warhammer_Dragonbone_Wrathman()                 { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x014C9E); }
    some<Weapon_t*> Warhammer_Dwarven()                             { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x01399A); }
    some<Weapon_t*> Warhammer_Ebony()                               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139B2); }
    some<Weapon_t*> Warhammer_Elven()                               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139A2); }
    some<Weapon_t*> Warhammer_Glass()                               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0139AA); }
    some<Weapon_t*> Warhammer_Iron()                                { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x013981); }
    some<Weapon_t*> Warhammer_Iron_Aegisbane()                      { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0D2AFE); }
    some<Weapon_t*> Warhammer_Orcish()                              { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x013992); }
    some<Weapon_t*> Warhammer_Orcish_Longhammer()                   { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0AE085); }
    some<Weapon_t*> Warhammer_Orcish_Shagrol()                      { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0223FB); }
    some<Weapon_t*> Warhammer_Steel()                               { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x01398A); }
    some<Weapon_t*> Warhammer_Steel_Dawnguard()                     { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x00DD55); }
    some<Weapon_t*> Warhammer_Steel_Dawnguard_Rune()                { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x011BAD); }
    some<Weapon_t*> Warhammer_Steel_Giant_Club_0()                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0461DA); }
    some<Weapon_t*> Warhammer_Steel_Giant_Club_1()                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0CDEC9); }
    some<Weapon_t*> Warhammer_Steel_Giant_Club_2()                  { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x0C334F); }
    some<Weapon_t*> Warhammer_Steel_Giant_Club_Frost()              { DEFINE_FORM(Const::Mod::Dawnguard(),      Weapon_t, 0x012D14); }
    some<Weapon_t*> Warhammer_Steel_Trollsbane()                    { DEFINE_FORM(Const::Mod::Skyrim(),         Weapon_t, 0x06AF63); }

}}}
